function [center_coord] = get_center(rect_coords) 
	
	center_coord = floor([rect_coords(1) + (rect_coords(3)-rect_coords(1))/2, ...
		rect_coords(2) + (rect_coords(4)-rect_coords(2))/2, ...
		rect_coords(1) + (rect_coords(3)-rect_coords(1))/2 + 1, ...
		rect_coords(2) + (rect_coords(4)-rect_coords(2))/2 + 1]);

